# Generated by Django 4.1.5 on 2023-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_rename_ulr_image_preview_product_url_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcessMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
    ]
