# Generated by Django 4.1.5 on 2023-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_status',
            field=models.CharField(default='available', max_length=12),
        ),
    ]
