# Generated by Django 4.1.5 on 2023-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=130)),
                ('old_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('href', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
