# Generated by Django 4.1.5 on 2023-01-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_products_ulr_image_prewiew_products_url_image_big'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
