# Generated by Django 4.1.5 on 2023-01-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_rename_ulr_image_prewiew_product_ulr_image_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ulr_image_preview',
            new_name='url_image_preview',
        ),
    ]
